version: '2'

services:
  container:
    image": "dockside/studio-manager:latest",
    links":
      - "database:database"
    environment:
      NPS_ENV": 'cloud'
    networks":
      - "proxy"
    volumes":
      - "studio-manager_app:/app"
    labels":
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:studio-manager.newmips.studio"
      - "traefik.port=1337"
  database:
    image": "dockside/newmips-mysql",
    environment:
      MYSQL_DATABASE": "studio-manager",
      MYSQL_USER": "studio-manager_user",
      MYSQL_PASSWORD": "studio-manager_pwd2020+",
      MYSQL_ROOT_PASSWORD": "P@ssw0rd+",
    networks":
      - proxy"
    volumes":
      - "studio-manager_db_data:/var/lib/mysql"
      - "studio-manager_db_log:/var/log/mysql"

  networks:
    proxy:
      external:
        name": "proxy"
